### ISSUE TITLE
Both "extract to function" and "extract to file" failed

### ISSUE THREAD

**Issue by Nohac** [fannheyward/coc-react-refactor#38]
I can't get any of the aforementioned functions to work, here's my `CocInfo` log:
```
## versions

vim version: NVIM v0.5.0-710-gb9ceac465
node version: v14.12.0
coc.nvim version: 0.0.79-be822b546f
coc.nvim directory: /home/user/.config/nvim/plug.vim/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-11-09T09:33:33.113 ERROR (pid:962707) [extension:coc-react-refactor] - Extract JSX to function: TypeError: coc_nvim_1.workspace.requestInput is not a function
    at Object.exports.askForName (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:75232:45)
    at exports.extractToFunction (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:69634:36)
    at CommandItem.execute (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24057:21)
    at CommandManager.executeCommand (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24395:44)
    at CommandManager.execute (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24335:29)
    at Handler.applyCodeAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:89637:36)
    at Handler.doCodeAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:89599:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin.cocAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24009:16)
    at async NeovimClient.<anonymous> (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:11597:21)
2020-11-09T09:33:43.847 INFO (pid:962707) [completion-complete] - Results from: around,snippets
2020-11-09T09:33:49.677 ERROR (pid:962707) [extension:coc-react-refactor] - Extract to file: TypeError: coc_nvim_1.workspace.requestInput is not a function
    at Object.exports.askForName (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:75232:45)
    at exports.extractToFile (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:69674:36)
    at CommandItem.execute (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24057:21)
    at CommandManager.executeCommand (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24395:44)
    at CommandManager.execute (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24335:29)
    at Handler.applyCodeAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:89637:36)
    at Handler.doCodeAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:89599:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin.cocAction (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:24009:16)
    at async NeovimClient.<anonymous> (/home/user/.config/nvim/plug.vim/coc.nvim/build/index.js:11597:21)
```

**Comment by fannheyward** [comment]
fixed in coc.nvim https://github.com/neoclide/coc.nvim/pull/2578

**Comment by Nohac** [comment]
Thank you for the quick response!
Unfortunately it's still not working, I'm getting a different error message now:
```
## versions

vim version: NVIM v0.5.0-710-gb9ceac465
node version: v14.12.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/user/.config/nvim/plug.vim/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-11-09T13:58:44.272 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:58:44.402 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:58:44.526 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:58:44.615 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:58:44.689 ERROR (pid:974021) [extension:coc-react-refactor] - Extract JSX to function: Error: Mode '' not supported
    at Workspace.getSelectedRange (/home/user/.config/nvim/plug.vim/coc.nvim/lib/workspace.js:626:19)
    at exports.extractToFunction (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:69641:50)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-09T13:59:17.038 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.191 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.339 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.407 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.624 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.740 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.878 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:17.947 WARN (pid:974021) [completion] - Document not attached, suggest disabled.
2020-11-09T13:59:18.119 ERROR (pid:974021) [extension:coc-react-refactor] - Extract to file: Error: Mode '' not supported
    at Workspace.getSelectedRange (/home/user/.config/nvim/plug.vim/coc.nvim/lib/workspace.js:626:19)
    at exports.extractToFile (/home/user/.config/coc/extensions/node_modules/coc-react-refactor/lib/index.js:69687:50)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by fannheyward** [comment]
You needs to select the code block what you want to extract.

**Comment by fannheyward** [comment]
Reproduced

**Comment by fannheyward** [comment]
Set `"coc.preferences.promptInput": false` in your coc-settings.json to fix this for now, this is a coc bug. https://github.com/neoclide/coc.nvim/issues/2582

**Comment by fannheyward** [comment]
Fixed on latest coc.nvim, please upgrade it.
